post/models.py
from flask_sqlalchemy import SQLAlchemy
from datetime import datetime

db = SQLAlchemy()



class Category(db.Model):
    __tablename__= 'category'
    id = db.Column(db.Integer, primary_key=True)
    cateoryName = db.Column(db.String(100))
    post = db.relationship('Post', backref='category', lazy=True)

    def __repr__(self):
        return f"{self.name}"

    @classmethod
    def get_all_Category(cls):
        return cls.query.all()

class Post(db.Model):
    __tablename__ = 'posts'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    body = db.Column(db.String(), nullable=False)
    description = db.Column(db.String(), nullable=False)
    image = db.Column(db.String(255), nullable=True,default='image.png')
    created_at = db.Column(db.DateTime, nullable=True, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=True, default=datetime.utcnow, onupdate=datetime.utcnow)
    category_id = db.Column(db.Integer, db.ForeignKey('category.id'), nullable= True,default=1)

    @staticmethod
    def create(title, body, description,image,created_at,updated_at,category_id):  
        new_post = Post(title=title, body=body, description=description,image=image,
                        created_at=created_at, updated_at=updated_at,category_id=category_id)
        db.session.add(new_post)
        db.session.commit()

    def __repr__(self):
        return f"Post {self.id}: {self.title}"
    
    def update_post(self, updated_data):
        self.title = updated_data["title"]
        self.body = updated_data["body"]
        self.description = updated_data["description"]
        db.session.add(self)
        db.session.commit()
        return True

post/post_crud/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,FileField


class PostForm(FlaskForm):
    title = StringField('Title')
    body = StringField('Body')
    description = StringField('Description')
    image = FileField('Image')


class CategoryForm(FlaskForm):
    categoryName = StringField('Category Name')

post/__init__.py
from flask import  Flask
from flask_migrate import Migrate
from post.models import  db
from post.config import  projectConfig as AppConfig  
from post.models import Post
from flask import  render_template
from post.post_crud.api.api_views import AllPosts,PostGetSpecificAndUpdateAndDelete

from flask_restful import Api

def create_app(config_name):
    app = Flask(__name__)
    current_config = AppConfig[config_name] 
    app.config['SQLALCHEMY_DATABASE_URI'] = current_config.SQLALCHEMY_DATABASE_URI
    app.config['SQLALCHEMY_DATABASE_URI'] = current_config
    app.config['SECRET_KEY'] = current_config.SECRET_KEY
    app.config.from_object(current_config)
    db.init_app(app)

    migrate = Migrate(app, db, render_as_batch=True)


    from post.post_crud import post_blueprint
    app.register_blueprint(post_blueprint)

    api = Api(app)
    api.add_resource(AllPosts, '/api/posts')
    api.add_resource(PostGetSpecificAndUpdateAndDelete, '/api/posts/<int:id>')



    return  app

post/post_crud/__init__.py
from flask import  Blueprint

post_blueprint= Blueprint('posts', __name__, url_prefix='/')

from post.post_crud import  views

post/post_crud/views.py
from flask import render_template,redirect,url_for,request
from post.models import Post,Category
from post.post_crud import  post_blueprint
from post.models import  db
from werkzeug.utils import secure_filename
import os
from .forms import PostForm,CategoryForm

@post_blueprint.route('/', endpoint='posts_all')
def all_Posts():
    posts = Post.query.all()
    return render_template('showPosts.html', posts=posts)


@post_blueprint.route('/posts/<id>', endpoint='post_details')
def post_info(id):
    post = Post.query.get_or_404(id)
    return render_template('showSpcificPost.html', post=post)

@post_blueprint.route('/posts/<id>/delete', endpoint='post_delete')
def post_delete(id):
    post = Post.query.get_or_404(id)
    db.session.delete(post)
    db.session.commit()
    return redirect('/')




@post_blueprint.route('/edit/<int:id>/', methods=('GET', 'POST'),endpoint="edit")
def edit(id):
    post=Post.query.get_or_404(id)
    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']
        description = request.form['description']
        # image=request.files['image']
        post.title=title
        post.body=body
        post.description= description
        # post.image= image
        db.session.add(post)
        db.session.commit()
        return redirect('/')
    return render_template('UpdatePost.html',post=post)



@post_blueprint.route('/addnewpost', methods = ['POST','GET'],endpoint="addnewpost")
def addNewPost():
    form  = PostForm()
    if request.method == 'GET':
        return render_template("addPost.html",form=form,category=Category.query.all())
    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']
        description = request.form['description']
        # image = request.files['image']
        # filename=secure_filename(image.filename)
        # image.save(os.path.join('static/images', filename))
        category = request.form['category']
        record = Post(title=title,
                          body=body,
                          description=description,
                          category_id=category) 
        
        db.session.add(record)
        db.session.commit()
        return redirect('/')
  

@post_blueprint.route('/addnewcategory', methods = ['POST','GET'],endpoint="addnewcategory")
def addNewCategory():
    formCat = CategoryForm()
    if request.method == 'GET':
        return render_template("addCategory.html",form=formCat)
    if request.method == 'POST':
        print(request.form)
        category = request.form['categoryName']
        record = Category(cateoryName=category)
        db.session.add(record)
        db.session.commit()
        return redirect('/')

post/templates/UpdatePost.html
{%  extends 'base.html' %}

{% block title %} Update Post {% endblock %}

    {% block content %}   

<div class="container text-light">
    <form method="POST"  >
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">Title</label>
          <input type="text" class="form-control" name="title" value="{{post.title}}" id="exampleInputEmail1">
        </div>
        <div class="mb-3">
            <label for="exampleInputEmail2" class="form-label">Body</label>
            <input type="text" class="form-control" name="body" value="{{post.body}}"  id="exampleInputEmail2">
          </div>
          <div class="mb-3">
            <label for="exampleInputEmail3" class="form-label">Description</label>
            <input type="text" class="form-control" name="description" value="{{post.description}}"  id="exampleInputEmail3">
          </div>
        <button type="submit" class="btn btn-outline-light w-25 mx-auto">Update</button>
      </form>
</div>
    {% endblock %}

post/templates/addCategory.html
{%  extends 'base.html' %}

{% block title %} Add New Category {% endblock %}

    {% block content %}   

<div class="container text-light">
    <form method="POST">
      {{form.csrf_token}}
      <div class="mb-3">
        <div class="form-label"> {{form.categoryName.label}}  </div>
        {{form.categoryName(value=categoryName, class='form-control')}}
        
        </div>

        <button type="submit" class="btn btn-outline-light w-25 mx-auto">Add New Category </button>
      </form>
</div>
    {% endblock %}

post/templates/addPost.html
{%  extends 'base.html' %}

{% block title %} Add New Post {% endblock %}

    {% block content %}   
<div class="container text-light">
  <form method="POST">
    {{form.csrf_token}}
<div class="mb-3">
<div class="form-label"> {{form.title.label}}  </div>
{{form.title(value=title, class='form-control')}}

</div>
<div class="mb-3">
<div class="form-label"> {{form.body.label}}  </div>
{{form.body( value=body, class='form-control')}}

</div>

    <div class="mb-3">

<div class="mb-3">
<div class="form-label"> {{form.description.label}}  </div>
{{form.description( value=description, class='form-control')}}
</div>

<div class="mb-3">
  <div class="form-label"> {{form.image.label}}  </div>
  {{form.image(value=image, class='form-control')}}
  
  </div>
<div class="mb-3 ">
  <label for="cat" class="form-label">Category</label>
<select name="category" class="form-control" id="cat">
  {% for cat in category %}
      <option value="{{cat.id}}">{{cat.cateoryName}}</option>
  {% endfor %}
</select></div>

  <button type="submit" class="btn btn-outline-light w-25 mx-auto">Add New Post</button>
</form>
</div>
    {% endblock %}

post/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">  
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <title>{% block title %} {% endblock %}</title>
</head>
<body style="background-color: gray;  color:#111 important;">
    <nav class="navbar navbar-expand-lg py-0">
        <div class="container-fluid p-2 text-light">
            <h1 class="navbar-brand" href="">Flask</h1>
            <button class="navbar-toggler bg-light" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item dropdown">
                        <a class="nav-link text-light" href="#" role="button">
                            Deliver
                            To Egypt <i class="fa-solid fa-location-pin "></i>
                        </a>
                    </li>
                </ul>
                <form class="d-flex w-75 d-none" role="search">
                    <input class="form-control me-2 d-none" type="search" placeholder="Search" aria-label="Search">
                </form>
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 d-none">
                    <li class="nav-item dropdown d-none">
                        <a class="nav-link dropdown-toggle text-light d-none" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            En
                        </a>
                        <ul class="dropdown-menu bg-dark d-none">
                            <li><a class="dropdown-item text-light bg-dark d-none"  href="#">Ar</a></li>
                            <li><a class="dropdown-item text-light bg-dark d-none" href="#">DE</a></li>
                        </ul>
                    </li>
                </ul>

                <ul class="navbar-nav me-auto mb-2 mb-lg-0 d-none">
                    <li class="nav-item dropdown d-none">
                      
                        <ul class="dropdown-menu bg-dark d-none">
                            
                        </ul>
                    </li>
                </ul>
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 d-none">
                    <li class="nav-item">
                        <a class="nav-link active text-light d-none" aria-current="page" href="#">Return<br>&Order </a>
                    </li>
    
    
                </ul>
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
                    <li class="nav-item dropdown">
                        <a class="nav-link  text-light" href="#" role="button" aria-expanded="false">
                            <i class="fa-solid fa-cart-shopping fa-2x"></i>
                            <span class="fw-bolder d-none">Cart</span>
                        </a>
    
                    </li>
                </ul>
            
            </div>
        </div>
    
    
    </nav>
    
    
    
    

    <nav class="navbar navbar-expand-lg navbar-light text-light">
        <div class="container-fluid">
            <i class="fa-solid fa-bars px-4 fa-3x " data-bs-toggle="offcanvas"
                data-bs-target="#offcanvasWithBothOptions" aria-controls="offcanvasWithBothOptions"></i>
            <button class="navbar-toggler bg-light" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse " id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active fs-5 px-3 text-light" aria-current="page" href="{{ url_for('posts.posts_all') }}">Posts
                            </a>
                    </li>
             
                     <li class="nav-item">
                        <a class="nav-link active fs-5 px-3  text-light" aria-current="page" href="{{ url_for('posts.addnewpost') }}">Add Post</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link active fs-5 px-3 text-light" aria-current="page" href="{{ url_for('posts.addnewcategory') }}">Add Category
                            </a>
                    </li>
            </div>
        </div>
    </nav>
    {% block content %} {% endblock %}
    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>
</html>

post/templates/macros.html
{% macro render_Full_Object(posts) %}
    {% for post in posts %}
    <div class="col-lg-3 col-md-4 my-3">
        
        <div class="card  rounded-3 text-center h-100" style="box-shadow:5px 5px 5px gray">
            <h3 class="card-title p-2 fw-bolder">{{post.title}}</h3>
            <h5 class="card-title p-2 fw-bolder">{{post.description}}</h5>
            <div class="card-body">
             <a class="btn btn-outline-info" href="{{ url_for('posts.post_details', id=post.id) }}">Show</a>
             <a class="btn btn-outline-secondary" href="{{ url_for('posts.edit', id=post.id) }}">Update</a>
             <a class="btn btn-outline-danger " href="{{ url_for('posts.post_delete', id=post.id) }}">Delete</a>
            </div>
        </div>
    </div>    
    {% endfor %}

{% endmacro %}

post/templates/not_found.html
{%  extends 'base.html' %}

{% block title %} Not Found {% endblock %}

    {% block content %} 
    <div class="container text-center">
        <div style="height: 100vh;width: 100wh;">

            <img src="{{ url_for('static', filename='images/notfound.png') }}" alt="Not Found">
        </div>
    </div>
    {% endblock %}

post/templates/showPosts.html
{%  extends 'base.html' %}

{% block title %} Database Products {% endblock %}

    {% block nav %}Home{% endblock %}


    {% block content %} 
    <div class="container ">
        <div class="row">
        {% import 'macros.html' as post %}
        {{post.render_Full_Object(posts)}}
    </div>
    </div>
    {% endblock %}

post/templates/showSpcificPost.html
{%  extends 'base.html' %}

{% block title %} {{post.title}} {% endblock %}

    {% block nav %}Home{% endblock %}{% block link %}{% endblock %}


    {% block content %} 

    <div class="container mt-5 text-light">
        <h1 class="fw-bolder text-light mb-4">{{post.title}}</h1>
    </div>
    <div class="container text-light">
        <div class="row">
            <table class="table table-striped text-light">
                <thead>
                    <tr class="text-light">
                      <th scope="col">Title</th>
                      <th scope="col">Body</th>
                      <th scope="col">Description</th>
                      <th scope="col">Create Time</th>
                      <th scope="col">Category</th>




                    </tr>
                  </thead>
                  <tbody>
                    <tr class="text-light">
                   
                      <td>{{post.title}} </td>
                      <td>{{post.body}} </td>
                      <td>{{post.description}}</td>
                      <td>{{post.created_at}}</td>
                      <td>{{post.category_id}}</td>


                      
                      
                      
                      
                    </tr>
                  </tbody>
                  
                </table>
      </div>
    </div>
    {% endblock %}